// *** Generated by OFS compiler version 2.0 *** 
import {Stream} from './combinadores.mjs';


const FOUR = 9;

let ten = 2 * FOUR + 1;

const printIt = (it) => console.log( it );

const tenNats = Stream.iterableCreator(0,  (n) => n + 1).cut(ten);

tenNats.map(printIt).forEach((e) => e);

