// *** Generated by OFS compiler version 2.0 *** 
import {Stream} from './combinadores.mjs';


const printIt = (it) => console.log( it );

const parity_map_50 = Stream.iterableCreator(0,  (n) => n + 1).cut(50).map((n) => ( n % 2 != 0 ) ? printIt( 'odd' ) : printIt( 'even' ));

parity_map_50.forEach((e) => e);

