cls
@ECHO OFF
cd osf-server
echo Installing Client Node_Modules.....
call npm install
echo Building Server.....
call npm run build
echo Starting Server.....
start npm run start
cd ..
cd osf-cliente
echo Installing Client Node_Modules.....
call npm install
echo Building Client.....
call npm run build
echo Starting Client.....
start npm start
cd ..